--- #YAML:1.0
name:                Data-Structure-Util
version:             0.15
abstract:            Change nature of data within a structure
license:             perl
author:              
    - Andy Armstrong <andy@hexten.net>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Digest::MD5:                   0
    Scalar::Util:                  1.01
    Test::More:                    0
    Test::Pod:                     0
    Test::Simple:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
no_index:
    package:
        - Devel::CheckLib
        - IO::CaptureOutput
